import logging
from typing import Optional, Tuple

import httpx
from tenacity import retry, stop_after_attempt, wait_exponential

from app.core.config import Settings

logger = logging.getLogger(__name__)

GITHUB_API_BASE = "https://api.github.com"

PRIORITY_LABEL_COLOR: dict[str, str] = {
    "Low": "0075ca",
    "Medium": "e4e669",
    "High": "d93f0b",
    "Critical": "b60205",
}


class GitHubService:
    def __init__(self, settings: Settings) -> None:
        self._token = settings.GITHUB_TOKEN
        self._owner = settings.GITHUB_OWNER
        self._repo = settings.GITHUB_REPO
        self._headers = {
            "Authorization": f"Bearer {self._token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }

    def _client(self) -> httpx.AsyncClient:
        return httpx.AsyncClient(base_url=GITHUB_API_BASE, headers=self._headers, timeout=30)

    @retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=2, max=8), reraise=True)
    async def create_issue(
        self,
        *,
        title: str,
        description: str,
        subtasks: list[str],
        priority: str,
        story_points: int,
        risks: list[str],
    ) -> Tuple[int, str]:
        """Returns (issue_number, issue_url)."""
        body = self._build_body(description, subtasks, story_points, risks)
        label_name = f"priority:{priority.lower()}"
        await self._ensure_label(label_name, PRIORITY_LABEL_COLOR.get(priority, "ededed"))

        payload = {
            "title": title,
            "body": body,
            "labels": [label_name, "ai-generated"],
        }
        async with self._client() as client:
            resp = await client.post(
                f"/repos/{self._owner}/{self._repo}/issues", json=payload
            )
            resp.raise_for_status()
            data = resp.json()

        issue_number: int = data["number"]
        issue_url: str = data["html_url"]
        logger.info("GitHub issue #%d created: %s", issue_number, issue_url)
        return issue_number, issue_url

    @retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=2, max=8), reraise=True)
    async def update_issue(self, issue_number: int, *, title: Optional[str] = None, body: Optional[str] = None) -> None:
        payload: dict = {}
        if title:
            payload["title"] = title
        if body:
            payload["body"] = body
        async with self._client() as client:
            resp = await client.patch(
                f"/repos/{self._owner}/{self._repo}/issues/{issue_number}", json=payload
            )
            resp.raise_for_status()
        logger.info("GitHub issue #%d updated", issue_number)

    @retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=2, max=8), reraise=True)
    async def close_issue(self, issue_number: int) -> None:
        async with self._client() as client:
            resp = await client.patch(
                f"/repos/{self._owner}/{self._repo}/issues/{issue_number}",
                json={"state": "closed"},
            )
            resp.raise_for_status()
        logger.info("GitHub issue #%d closed", issue_number)

    # ── Private helpers ───────────────────────────────────────────────────────

    async def _ensure_label(self, name: str, color: str) -> None:
        async with self._client() as client:
            resp = await client.get(
                f"/repos/{self._owner}/{self._repo}/labels/{name}"
            )
            if resp.status_code == 404:
                await client.post(
                    f"/repos/{self._owner}/{self._repo}/labels",
                    json={"name": name, "color": color},
                )

    @staticmethod
    def _build_body(description: str, subtasks: list[str], story_points: int, risks: list[str]) -> str:
        lines: list[str] = [
            f"## Description\n{description}\n",
            f"**Story Points:** {story_points}\n",
        ]
        if subtasks:
            lines.append("## Subtasks")
            for st in subtasks:
                lines.append(f"- [ ] {st}")
            lines.append("")
        if risks:
            lines.append("## Risks & Blockers")
            for risk in risks:
                lines.append(f"- {risk}")
            lines.append("")
        lines.append("---\n*Generated by AI Project Manager*")
        return "\n".join(lines)
